<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>UclOpen HardwareSimulation Bonsai library.</Description>
    <PackageTags>$(PackageTags) Harp Simulation</PackageTags>
    <TargetFrameworks>net472</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Bonsai.Harp" Version="3.6.1" />
    <PackageReference Include="Harp.Behavior" Version="0.2.0" />
  </ItemGroup>

</Project>
