//----------------------
// <auto-generated>
//     Generated using the NJsonSchema v10.9.0.0 (Newtonsoft.Json v13.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------


namespace UclOpen.Pyrat
{
    #pragma warning disable // Disable all warnings

    /// <summary>
    /// A comment entry as returned in a PyRAT record.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.7.2.0 (Newtonsoft.Json v13.0.0.0)")]
    [System.ComponentModel.DescriptionAttribute("A comment entry as returned in a PyRAT record.")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    [Bonsai.CombinatorAttribute(MethodName="Generate")]
    public partial class Comment
    {
    
        private System.DateTimeOffset? _created;
    
        private string _content;
    
        public Comment()
        {
            _content = "";
        }
    
        protected Comment(Comment other)
        {
            _created = other._created;
            _content = other._content;
        }
    
        /// <summary>
        /// UTC datetime of the comment.
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Newtonsoft.Json.JsonPropertyAttribute("created")]
        [System.ComponentModel.DescriptionAttribute("UTC datetime of the comment.")]
        public System.DateTimeOffset? Created
        {
            get
            {
                return _created;
            }
            set
            {
                _created = value;
            }
        }
    
        /// <summary>
        /// Comment text.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("content")]
        [System.ComponentModel.DescriptionAttribute("Comment text.")]
        public string Content
        {
            get
            {
                return _content;
            }
            set
            {
                _content = value;
            }
        }
    
        public System.IObservable<Comment> Generate()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new Comment(this)));
        }
    
        public System.IObservable<Comment> Generate<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new Comment(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("Created = " + _created + ", ");
            stringBuilder.Append("Content = " + _content);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    /// <summary>
    /// A single mutation entry as returned in a PyRAT record.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.7.2.0 (Newtonsoft.Json v13.0.0.0)")]
    [System.ComponentModel.DescriptionAttribute("A single mutation entry as returned in a PyRAT record.")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    [Bonsai.CombinatorAttribute(MethodName="Generate")]
    public partial class Mutation
    {
    
        private string _mutationname;
    
        private string _mutationgrade;
    
        public Mutation()
        {
        }
    
        protected Mutation(Mutation other)
        {
            _mutationname = other._mutationname;
            _mutationgrade = other._mutationgrade;
        }
    
        /// <summary>
        /// Name of the mutation.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("mutationname", Required=Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DescriptionAttribute("Name of the mutation.")]
        public string Mutationname
        {
            get
            {
                return _mutationname;
            }
            set
            {
                _mutationname = value;
            }
        }
    
        /// <summary>
        /// Grade: wt, het, hom, etc.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("mutationgrade", Required=Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DescriptionAttribute("Grade: wt, het, hom, etc.")]
        public string Mutationgrade
        {
            get
            {
                return _mutationgrade;
            }
            set
            {
                _mutationgrade = value;
            }
        }
    
        public System.IObservable<Mutation> Generate()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new Mutation(this)));
        }
    
        public System.IObservable<Mutation> Generate<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new Mutation(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("Mutationname = " + _mutationname + ", ");
            stringBuilder.Append("Mutationgrade = " + _mutationgrade);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    /// <summary>
    /// Subject record from PyRAT. Matches the self.info dict structure in the GUI.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.7.2.0 (Newtonsoft.Json v13.0.0.0)")]
    [System.ComponentModel.DescriptionAttribute("Subject record from PyRAT. Matches the self.info dict structure in the GUI.")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    [Bonsai.CombinatorAttribute(MethodName="Generate")]
    public partial class PyRatSubject
    {
    
        private string _eartagOrId;
    
        private string _labid;
    
        private string _sex;
    
        private double? _weight;
    
        private int? _ageDays;
    
        private int? _ageWeeks;
    
        private string _strainNameWithId;
    
        private string _responsibleFullname;
    
        private string _responsibleId;
    
        private System.Collections.Generic.List<Mutation> _mutations;
    
        private string _cagenumber;
    
        private string _cagetype;
    
        private string _roomName;
    
        private string _dateLastComment;
    
        private System.Collections.Generic.List<Comment> _comments;
    
        public PyRatSubject()
        {
            _mutations = new System.Collections.Generic.List<Mutation>();
            _comments = new System.Collections.Generic.List<Comment>();
        }
    
        protected PyRatSubject(PyRatSubject other)
        {
            _eartagOrId = other._eartagOrId;
            _labid = other._labid;
            _sex = other._sex;
            _weight = other._weight;
            _ageDays = other._ageDays;
            _ageWeeks = other._ageWeeks;
            _strainNameWithId = other._strainNameWithId;
            _responsibleFullname = other._responsibleFullname;
            _responsibleId = other._responsibleId;
            _mutations = other._mutations;
            _cagenumber = other._cagenumber;
            _cagetype = other._cagetype;
            _roomName = other._roomName;
            _dateLastComment = other._dateLastComment;
            _comments = other._comments;
        }
    
        /// <summary>
        /// PyRAT eartag or ID.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("eartagOrId", Required=Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DescriptionAttribute("PyRAT eartag or ID.")]
        public string EartagOrId
        {
            get
            {
                return _eartagOrId;
            }
            set
            {
                _eartagOrId = value;
            }
        }
    
        /// <summary>
        /// Lab ID.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("labid")]
        [System.ComponentModel.DescriptionAttribute("Lab ID.")]
        public string Labid
        {
            get
            {
                return _labid;
            }
            set
            {
                _labid = value;
            }
        }
    
        /// <summary>
        /// Biological sex.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("sex")]
        [System.ComponentModel.DescriptionAttribute("Biological sex.")]
        public string Sex
        {
            get
            {
                return _sex;
            }
            set
            {
                _sex = value;
            }
        }
    
        /// <summary>
        /// Most recent weight in grams.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("weight")]
        [System.ComponentModel.DescriptionAttribute("Most recent weight in grams.")]
        public double? Weight
        {
            get
            {
                return _weight;
            }
            set
            {
                _weight = value;
            }
        }
    
        /// <summary>
        /// Age in days.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("ageDays")]
        [System.ComponentModel.DescriptionAttribute("Age in days.")]
        public int? AgeDays
        {
            get
            {
                return _ageDays;
            }
            set
            {
                _ageDays = value;
            }
        }
    
        /// <summary>
        /// Age in weeks.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("ageWeeks")]
        [System.ComponentModel.DescriptionAttribute("Age in weeks.")]
        public int? AgeWeeks
        {
            get
            {
                return _ageWeeks;
            }
            set
            {
                _ageWeeks = value;
            }
        }
    
        /// <summary>
        /// Strain name with ID.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("strainNameWithId")]
        [System.ComponentModel.DescriptionAttribute("Strain name with ID.")]
        public string StrainNameWithId
        {
            get
            {
                return _strainNameWithId;
            }
            set
            {
                _strainNameWithId = value;
            }
        }
    
        /// <summary>
        /// Responsible researcher.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("responsibleFullname")]
        [System.ComponentModel.DescriptionAttribute("Responsible researcher.")]
        public string ResponsibleFullname
        {
            get
            {
                return _responsibleFullname;
            }
            set
            {
                _responsibleFullname = value;
            }
        }
    
        /// <summary>
        /// Responsible researcher ID.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("responsibleId")]
        [System.ComponentModel.DescriptionAttribute("Responsible researcher ID.")]
        public string ResponsibleId
        {
            get
            {
                return _responsibleId;
            }
            set
            {
                _responsibleId = value;
            }
        }
    
        /// <summary>
        /// Mutations.
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Newtonsoft.Json.JsonPropertyAttribute("mutations")]
        [System.ComponentModel.DescriptionAttribute("Mutations.")]
        public System.Collections.Generic.List<Mutation> Mutations
        {
            get
            {
                return _mutations;
            }
            set
            {
                _mutations = value;
            }
        }
    
        /// <summary>
        /// Cage number.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("cagenumber")]
        [System.ComponentModel.DescriptionAttribute("Cage number.")]
        public string Cagenumber
        {
            get
            {
                return _cagenumber;
            }
            set
            {
                _cagenumber = value;
            }
        }
    
        /// <summary>
        /// Cage type.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("cagetype")]
        [System.ComponentModel.DescriptionAttribute("Cage type.")]
        public string Cagetype
        {
            get
            {
                return _cagetype;
            }
            set
            {
                _cagetype = value;
            }
        }
    
        /// <summary>
        /// Room name.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("roomName")]
        [System.ComponentModel.DescriptionAttribute("Room name.")]
        public string RoomName
        {
            get
            {
                return _roomName;
            }
            set
            {
                _roomName = value;
            }
        }
    
        /// <summary>
        /// Date of last comment.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("dateLastComment")]
        [System.ComponentModel.DescriptionAttribute("Date of last comment.")]
        public string DateLastComment
        {
            get
            {
                return _dateLastComment;
            }
            set
            {
                _dateLastComment = value;
            }
        }
    
        /// <summary>
        /// Recent comments.
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Newtonsoft.Json.JsonPropertyAttribute("comments")]
        [System.ComponentModel.DescriptionAttribute("Recent comments.")]
        public System.Collections.Generic.List<Comment> Comments
        {
            get
            {
                return _comments;
            }
            set
            {
                _comments = value;
            }
        }
    
        public System.IObservable<PyRatSubject> Generate()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new PyRatSubject(this)));
        }
    
        public System.IObservable<PyRatSubject> Generate<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new PyRatSubject(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("EartagOrId = " + _eartagOrId + ", ");
            stringBuilder.Append("Labid = " + _labid + ", ");
            stringBuilder.Append("Sex = " + _sex + ", ");
            stringBuilder.Append("Weight = " + _weight + ", ");
            stringBuilder.Append("AgeDays = " + _ageDays + ", ");
            stringBuilder.Append("AgeWeeks = " + _ageWeeks + ", ");
            stringBuilder.Append("StrainNameWithId = " + _strainNameWithId + ", ");
            stringBuilder.Append("ResponsibleFullname = " + _responsibleFullname + ", ");
            stringBuilder.Append("ResponsibleId = " + _responsibleId + ", ");
            stringBuilder.Append("Mutations = " + _mutations + ", ");
            stringBuilder.Append("Cagenumber = " + _cagenumber + ", ");
            stringBuilder.Append("Cagetype = " + _cagetype + ", ");
            stringBuilder.Append("RoomName = " + _roomName + ", ");
            stringBuilder.Append("DateLastComment = " + _dateLastComment + ", ");
            stringBuilder.Append("Comments = " + _comments);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    /// <summary>
    /// Written to JSON by Python pre-session. Bonsai reads and rewrites the full
    ///JSON post-session with water_delivered_ml, comment, and session_end populated.
    ///Python re-reads it to pre-populate the post-session confirmation dialog,
    ///then posts water and comment to PyRAT.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.7.2.0 (Newtonsoft.Json v13.0.0.0)")]
    [System.ComponentModel.DescriptionAttribute(@"Written to JSON by Python pre-session. Bonsai reads and rewrites the full
    JSON post-session with water_delivered_ml, comment, and session_end populated.
    Python re-reads it to pre-populate the post-session confirmation dialog,
    then posts water and comment to PyRAT.")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    [Bonsai.CombinatorAttribute(MethodName="Generate")]
    public partial class SessionConfig
    {
    
        private PyRatSubject _subject;
    
        private System.DateTimeOffset _sessionStart;
    
        private string _workflow;
    
        private double? _waterDeliveredMl;
    
        private string _comment;
    
        private System.DateTimeOffset? _sessionEnd;
    
        private System.Collections.Generic.List<Comment> _comments;
    
        public SessionConfig()
        {
            _subject = new PyRatSubject();
            _comments = new System.Collections.Generic.List<Comment>();
        }
    
        protected SessionConfig(SessionConfig other)
        {
            _subject = other._subject;
            _sessionStart = other._sessionStart;
            _workflow = other._workflow;
            _waterDeliveredMl = other._waterDeliveredMl;
            _comment = other._comment;
            _sessionEnd = other._sessionEnd;
            _comments = other._comments;
        }
    
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Newtonsoft.Json.JsonPropertyAttribute("subject", Required=Newtonsoft.Json.Required.Always)]
        public PyRatSubject Subject
        {
            get
            {
                return _subject;
            }
            set
            {
                _subject = value;
            }
        }
    
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Newtonsoft.Json.JsonPropertyAttribute("sessionStart", Required=Newtonsoft.Json.Required.Always)]
        public System.DateTimeOffset SessionStart
        {
            get
            {
                return _sessionStart;
            }
            set
            {
                _sessionStart = value;
            }
        }
    
        [Newtonsoft.Json.JsonIgnoreAttribute()]
        [System.ComponentModel.BrowsableAttribute(false)]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("SessionStart")]
        public string SessionStartXml
        {
            get
            {
                return _sessionStart.ToString("o");
            }
            set
            {
                _sessionStart = System.DateTimeOffset.Parse(value);
            }
        }
    
        [Newtonsoft.Json.JsonPropertyAttribute("workflow", Required=Newtonsoft.Json.Required.Always)]
        public string Workflow
        {
            get
            {
                return _workflow;
            }
            set
            {
                _workflow = value;
            }
        }
    
        [Newtonsoft.Json.JsonPropertyAttribute("waterDeliveredMl")]
        public double? WaterDeliveredMl
        {
            get
            {
                return _waterDeliveredMl;
            }
            set
            {
                _waterDeliveredMl = value;
            }
        }
    
        [Newtonsoft.Json.JsonPropertyAttribute("comment")]
        public string Comment
        {
            get
            {
                return _comment;
            }
            set
            {
                _comment = value;
            }
        }
    
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Newtonsoft.Json.JsonPropertyAttribute("sessionEnd")]
        public System.DateTimeOffset? SessionEnd
        {
            get
            {
                return _sessionEnd;
            }
            set
            {
                _sessionEnd = value;
            }
        }
    
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Newtonsoft.Json.JsonPropertyAttribute("comments")]
        public System.Collections.Generic.List<Comment> Comments
        {
            get
            {
                return _comments;
            }
            set
            {
                _comments = value;
            }
        }
    
        public System.IObservable<SessionConfig> Generate()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new SessionConfig(this)));
        }
    
        public System.IObservable<SessionConfig> Generate<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new SessionConfig(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("Subject = " + _subject + ", ");
            stringBuilder.Append("SessionStart = " + _sessionStart + ", ");
            stringBuilder.Append("Workflow = " + _workflow + ", ");
            stringBuilder.Append("WaterDeliveredMl = " + _waterDeliveredMl + ", ");
            stringBuilder.Append("Comment = " + _comment + ", ");
            stringBuilder.Append("SessionEnd = " + _sessionEnd + ", ");
            stringBuilder.Append("Comments = " + _comments);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    /// <summary>
    /// Serializes a sequence of data model objects into JSON strings.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.7.2.0 (Newtonsoft.Json v13.0.0.0)")]
    [System.ComponentModel.DescriptionAttribute("Serializes a sequence of data model objects into JSON strings.")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Transform)]
    [Bonsai.CombinatorAttribute()]
    public partial class SerializeToJson
    {
    
        public Newtonsoft.Json.Formatting Formatting { get; set; }

        private System.IObservable<string> Process<T>(System.IObservable<T> source)
        {
            var formatting = Formatting;
            return System.Reactive.Linq.Observable.Select(source, value => Newtonsoft.Json.JsonConvert.SerializeObject(value, formatting));
        }

        public System.IObservable<string> Process(System.IObservable<Comment> source)
        {
            return Process<Comment>(source);
        }

        public System.IObservable<string> Process(System.IObservable<Mutation> source)
        {
            return Process<Mutation>(source);
        }

        public System.IObservable<string> Process(System.IObservable<PyRatSubject> source)
        {
            return Process<PyRatSubject>(source);
        }

        public System.IObservable<string> Process(System.IObservable<SessionConfig> source)
        {
            return Process<SessionConfig>(source);
        }
    }


    /// <summary>
    /// Deserializes a sequence of JSON strings into data model objects.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.7.2.0 (Newtonsoft.Json v13.0.0.0)")]
    [System.ComponentModel.DescriptionAttribute("Deserializes a sequence of JSON strings into data model objects.")]
    [System.ComponentModel.DefaultPropertyAttribute("Type")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Transform)]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<Comment>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<Mutation>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<PyRatSubject>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<SessionConfig>))]
    public partial class DeserializeFromJson : Bonsai.Expressions.SingleArgumentExpressionBuilder
    {
    
        public DeserializeFromJson()
        {
            Type = new Bonsai.Expressions.TypeMapping<SessionConfig>();
        }

        public Bonsai.Expressions.TypeMapping Type { get; set; }

        public override System.Linq.Expressions.Expression Build(System.Collections.Generic.IEnumerable<System.Linq.Expressions.Expression> arguments)
        {
            var typeMapping = (Bonsai.Expressions.TypeMapping)Type;
            var returnType = typeMapping.GetType().GetGenericArguments()[0];
            return System.Linq.Expressions.Expression.Call(
                typeof(DeserializeFromJson),
                "Process",
                new System.Type[] { returnType },
                System.Linq.Enumerable.Single(arguments));
        }

        private static System.IObservable<T> Process<T>(System.IObservable<string> source)
        {
            return System.Reactive.Linq.Observable.Select(source, value => Newtonsoft.Json.JsonConvert.DeserializeObject<T>(value));
        }
    }
}